"use client";
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, CheckCircle2, LoaderCircle } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { z } from 'zod';
const draftSchema=z.object({website:z.string().max(500).optional(),problem:z.string().max(3000).optional(),aiUsage:z.string().max(500).optional(),phone:z.string().max(20).optional()}).strict();
export function ApplicationForm(){const [fields,setFields]=useState({website:'',problem:'',aiUsage:'',phone:''});const [consent,setConsent]=useState(false);const [pending,setPending]=useState(false);const [error,setError]=useState('');const [receipt,setReceipt]=useState('');const requestId=useRef('');const form=useRef<HTMLFormElement>(null);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();try{void Promise.resolve(context.registerTool({name:'prepare_consultation_application',title:'상담 신청 내용 준비',description:'Fill the visible consultation form for the user to review. Does not give consent, submit, or store an application.',inputSchema:{type:'object',properties:{website:{type:'string',maxLength:500},problem:{type:'string',maxLength:3000},aiUsage:{type:'string',maxLength:500},phone:{type:'string',maxLength:20}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input:unknown){const parsed=draftSchema.safeParse(input);if(!parsed.success)return {prepared:false,error:'Invalid draft fields'};setFields(prev=>({...prev,...parsed.data}));setConsent(false);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {prepared:true,submitted:false,requiresUserReview:true}}},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort()},[]);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(pending)return;setError('');if(!consent){setError('개인정보 수집·이용 안내를 확인하고 동의해 주세요.');return}if(!requestId.current)requestId.current=crypto.randomUUID();setPending(true);try{const response=await fetch('/api/applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,id:requestId.current,consent,companyFax:new FormData(event.currentTarget).get('companyFax')||''})});const data=await response.json() as {id:string;received?:boolean;error?:string};if(!response.ok||!data.received)throw new Error(data.error||'접수 여부를 확인하지 못했습니다. 입력한 내용은 남아 있으니 다시 제출해 주세요.');setReceipt(data.id);setFields({website:'',problem:'',aiUsage:'',phone:''});setConsent(false);}catch(e){setError(e instanceof Error?e.message:'연결을 확인하고 다시 제출해 주세요. 입력한 내용은 남아 있습니다.')}finally{setPending(false)}}
 if(receipt)return <div className="application-success" role="status"><CheckCircle2 size={36}/><h2>상담 신청이 접수되었습니다.</h2><p>신청서를 읽어본 뒤 카카오톡으로 연락드리겠습니다. 카카오톡 연결이 어려우면 남겨주신 번호로 문자 안내를 드립니다.</p><p>연락을 드리면 상담 가능한 날짜와 시간을 말씀해주세요. 일정을 정한 뒤 Zoom으로 상담합니다.</p><p className="meta">접수번호 {receipt.slice(0,8).toUpperCase()}</p><Link href="/" className="button button-ink">홈으로 돌아가기</Link></div>;
 return <form ref={form} onSubmit={submit} className="application-form" aria-label="무료 상담 신청서"><div className="form-field"><label htmlFor="website">운영 중인 사이트 주소</label><p id="website-help">쇼핑몰, 홈페이지, 판매처 또는 사업용 블로그 주소를 적어주세요.</p><Input id="website" name="website" type="url" required maxLength={500} placeholder="https://" autoComplete="url" aria-describedby="website-help" value={fields.website} onChange={e=>setFields({...fields,website:e.target.value})}/></div><div className="form-field"><label htmlFor="problem">상담하고 싶은 내용</label><p id="problem-help">하고 싶은 일이나 어려운 점을 10자 이상 적어주세요. 자세한 내용은 상담하면서 여쭤보겠습니다.</p><Textarea id="problem" name="problem" required minLength={10} maxLength={3000} rows={5} aria-describedby="problem-help" placeholder="예: 상품 설명과 블로그 글을 직접 쓰고 싶습니다. AI를 써봤는데 문장이 어색해서 고치는 데 시간이 오래 걸립니다." value={fields.problem} onChange={e=>setFields({...fields,problem:e.target.value})}/></div><div className="form-field"><label htmlFor="aiUsage">AI 사용 경험</label><p id="ai-help">써본 프로그램과 용도를 적어주세요. 처음이시면 ‘사용한 적 없음’이라고 적어주시면 됩니다.</p><Textarea id="aiUsage" name="aiUsage" required maxLength={500} rows={2} aria-describedby="ai-help" value={fields.aiUsage} onChange={e=>setFields({...fields,aiUsage:e.target.value})}/></div><div className="form-field"><label htmlFor="phone">연락받으실 휴대전화번호</label><p id="phone-help">카카오톡으로 상담 일정을 안내합니다. 연결이 어려우면 문자로 연락드립니다.</p><Input id="phone" name="phone" type="tel" inputMode="tel" autoComplete="tel" required pattern="01[016789][ -]?[0-9]{3,4}[ -]?[0-9]{4}" placeholder="010-0000-0000" aria-describedby="phone-help" value={fields.phone} onChange={e=>setFields({...fields,phone:e.target.value})}/></div><div className="honeypot" aria-hidden="true"><label htmlFor="companyFax">회사 팩스</label><input id="companyFax" name="companyFax" autoComplete="off" tabIndex={-1}/></div><div className="privacy-consent"><div><Checkbox id="consent" checked={consent} onCheckedChange={value=>setConsent(value===true)} className="consent-checkbox"/><label htmlFor="consent">상담을 위한 개인정보 수집·이용에 동의합니다. <span>(필수)</span></label></div><p>세온비즈는 입력한 연락처와 사업 정보, 상담 내용을 신청 검토와 일정 조율에 사용합니다. 상담 목적을 달성하면 삭제합니다. 동의를 거부할 수 있으나 온라인 상담 신청은 제한됩니다.</p><Link href="/privacy" target="_blank" className="text-link">개인정보 안내 보기</Link></div>{error&&<p role="alert" className="form-error">{error}</p>}<button type="submit" disabled={pending} className="button button-coral submit-button">{pending?<><LoaderCircle className="spin" size={20}/> 접수 중</>:<>1시간 무료 상담 신청하기 <ArrowUpRight size={20}/></>}</button><p className="meta">상담 신청 시 결제되는 금액은 없습니다. 상담 일정은 연락을 드린 뒤 정합니다.</p></form>
}
