"use client";
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, CheckCircle2, LoaderCircle } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { z } from 'zod';
const draftSchema=z.object({website:z.string().max(500).optional(),problem:z.string().max(3000).optional(),aiUsage:z.string().max(500).optional(),phone:z.string().max(20).optional()}).strict();
export function ApplicationForm(){const [fields,setFields]=useState({website:'',problem:'',aiUsage:'',phone:''});const [consent,setConsent]=useState(false);const [pending,setPending]=useState(false);const [error,setError]=useState('');const [receipt,setReceipt]=useState('');const requestId=useRef('');const form=useRef<HTMLFormElement>(null);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();try{void Promise.resolve(context.registerTool({name:'prepare_consultation_application',title:'상담 신청 내용 준비',description:'Fill the visible consultation form for the user to review. Does not give consent, submit, or store an application.',inputSchema:{type:'object',properties:{website:{type:'string',maxLength:500},problem:{type:'string',maxLength:3000},aiUsage:{type:'string',maxLength:500},phone:{type:'string',maxLength:20}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input:unknown){const parsed=draftSchema.safeParse(input);if(!parsed.success)return {prepared:false,error:'Invalid draft fields'};setFields(prev=>({...prev,...parsed.data}));setConsent(false);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {prepared:true,submitted:false,requiresUserReview:true}}},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort()},[]);
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(pending)return;setError('');if(!consent){setError('개인정보 수집·이용 안내를 확인하고 동의해 주세요.');return}if(!requestId.current)requestId.current=crypto.randomUUID();setPending(true);try{const response=await fetch('/api/applications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...fields,id:requestId.current,consent,companyFax:new FormData(event.currentTarget).get('companyFax')||''})});const data=await response.json() as {id:string;received?:boolean;error?:string};if(!response.ok||!data.received)throw new Error(data.error||'접수 결과를 확인하지 못했습니다. 다시 시도해 주세요.');setReceipt(data.id);setFields({website:'',problem:'',aiUsage:'',phone:''});setConsent(false);}catch(e){setError(e instanceof Error?e.message:'연결을 확인한 뒤 다시 시도해 주세요.')}finally{setPending(false)}}
 if(receipt)return <div className="application-success" role="status"><CheckCircle2 size={36}/><h2>상담 신청이 접수되었습니다.</h2><p>내용을 확인한 뒤 입력하신 연락처로 카카오톡 연락을 드립니다. 연결이 어려우면 문자로 안내합니다.</p><p>상담 일정은 개별 연락 후 확정됩니다.</p><p className="meta">접수번호 {receipt.slice(0,8).toUpperCase()}</p><Link href="/" className="button button-ink">홈으로 돌아가기</Link></div>;
 return <form ref={form} onSubmit={submit} className="application-form" aria-label="무료 상담 신청서"><div className="form-field"><label htmlFor="website">사업의 웹사이트·쇼핑몰 주소</label><p id="website-help">자사몰, 판매처, 홈페이지 또는 사업용 채널 주소를 알려주세요.</p><Input id="website" name="website" type="url" required maxLength={500} placeholder="https://" autoComplete="url" aria-describedby="website-help" value={fields.website} onChange={e=>setFields({...fields,website:e.target.value})}/></div><div className="form-field"><label htmlFor="problem">가장 먼저 해결하고 싶은 문제</label><p id="problem-help">지금 막히는 일과 이번 상담에서 확인하고 싶은 내용을 10자 이상 적어주세요.</p><Textarea id="problem" name="problem" required minLength={10} maxLength={3000} rows={5} aria-describedby="problem-help" placeholder="예: 상품의 장점을 상세페이지에 어떻게 설명할지 고민입니다." value={fields.problem} onChange={e=>setFields({...fields,problem:e.target.value})}/></div><div className="form-field"><label htmlFor="aiUsage">현재 AI 사용 정도</label><p id="ai-help">사용 중인 도구와 하는 일을 적어주세요. 처음이라면 ‘처음 사용합니다’라고 적어주셔도 됩니다.</p><Textarea id="aiUsage" name="aiUsage" required maxLength={500} rows={2} aria-describedby="ai-help" value={fields.aiUsage} onChange={e=>setFields({...fields,aiUsage:e.target.value})}/></div><div className="form-field"><label htmlFor="phone">연락 가능한 휴대전화번호</label><p id="phone-help">카카오톡으로 연락하고, 연결되지 않으면 문자로 안내합니다.</p><Input id="phone" name="phone" type="tel" inputMode="tel" autoComplete="tel" required pattern="01[016789][ -]?[0-9]{3,4}[ -]?[0-9]{4}" placeholder="010-0000-0000" aria-describedby="phone-help" value={fields.phone} onChange={e=>setFields({...fields,phone:e.target.value})}/></div><div className="honeypot" aria-hidden="true"><label htmlFor="companyFax">회사 팩스</label><input id="companyFax" name="companyFax" autoComplete="off" tabIndex={-1}/></div><div className="privacy-consent"><div><Checkbox id="consent" checked={consent} onCheckedChange={value=>setConsent(value===true)} className="consent-checkbox"/><label htmlFor="consent">상담을 위한 개인정보 수집·이용에 동의합니다. <span>(필수)</span></label></div><p>세온비즈는 입력한 연락처와 사업 정보, 상담 내용을 신청 검토와 일정 조율에 사용합니다. 상담 목적을 달성하면 삭제합니다. 동의를 거부할 수 있으나 온라인 상담 신청은 제한됩니다.</p><Link href="/privacy" target="_blank" className="text-link">개인정보 안내 보기</Link></div>{error&&<p role="alert" className="form-error">{error}</p>}<button type="submit" disabled={pending} className="button button-coral submit-button">{pending?<><LoaderCircle className="spin" size={20}/> 접수 중</>:<>무료 상담 신청하기 <ArrowUpRight size={20}/></>}</button><p className="meta">신청만으로 유료 코칭 결제나 상담 일정이 확정되지 않습니다.</p></form>
}
