"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { ArrowUpRight, ArrowRight } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
export function Reveal({children,className=""}:{children:React.ReactNode;className?:string}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const el=ref.current;if(!el||matchMedia('(prefers-reduced-motion: reduce)').matches)return;el.classList.add('reveal-ready');const observer=new IntersectionObserver(es=>{if(es.some(e=>e.isIntersecting)){el.classList.add('revealed');observer.disconnect()}},{threshold:.12});observer.observe(el);return()=>observer.disconnect()},[]);return <div ref={ref} className={className}>{children}</div>}
export function SearchFigures(){return <div className="search-figures"><figure><figcaption><span>2021.05.23 — 06.22</span><strong>클릭 651회</strong></figcaption><img src="/images/search-2021.webp" width="1024" height="457" alt="2021년 서치콘솔: 웹 검색 클릭 651회, 노출 3.25만 회" loading="lazy"/></figure><figure><figcaption><span>2022.05.23 — 06.22</span><strong>클릭 약 2,840회</strong></figcaption><img src="/images/search-2022.webp" width="1024" height="456" alt="2022년 서치콘솔: 웹 검색 클릭 2.84천 회, 노출 19.1만 회" loading="lazy"/></figure></div>}
export function WorkShowcase(){const [scene,setScene]=useState("search");const ref=useRef<HTMLElement>(null);useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const el=ref.current;if(!el)return;let frame=0;const update=()=>{frame=0;const b=el.getBoundingClientRect();const p=Math.min(1,Math.max(0,(innerHeight-b.top)/(innerHeight*.8)));el.style.setProperty('--work-inset',`${(1-p)*3.5}%`);el.style.setProperty('--work-radius',`${(1-p)*32}px`)};const onScroll=()=>{if(!frame)frame=requestAnimationFrame(update)};addEventListener('scroll',onScroll,{passive:true});update();return()=>{removeEventListener('scroll',onScroll);cancelAnimationFrame(frame)}},[]);return <section ref={ref} className="work-showcase" data-scene={scene}><div className="container work-inner"><Reveal><div className="work-heading"><div><p className="eyebrow">세온비즈가 해온 일</p><h2>직접 작업한 내용과<br/>결과를 보여드립니다.</h2></div><p>식품 쇼핑몰의 상품 정보를 고친 일,<br/>원고를 짧은 영상으로 만든 일을<br/>실제 자료와 함께 소개합니다.</p></div></Reveal><Tabs value={scene} onValueChange={setScene} className="work-tabs"><TabsList variant="line" aria-label="실제 작업 자료" className="work-tabs-list"><TabsTrigger value="search" id="work-tab-search" aria-controls="work-panel-search">검색 데이터</TabsTrigger><TabsTrigger value="content" id="work-tab-content" aria-controls="work-panel-content">콘텐츠 제작</TabsTrigger></TabsList><div className="work-stage"><TabsContent value="search" id="work-panel-search" aria-labelledby="work-tab-search" className="work-panel"><SearchFigures/><div className="work-caption"><div><p className="kicker">고객 사례 · 식품 쇼핑몰</p><h3>구글 검색 클릭 651회 → 약 2,840회</h3></div><p>상품 제목과 설명, 이미지 정보를 정비하며 살펴본 식품 쇼핑몰의 기록입니다. 2021년과 2022년의 같은 날짜 구간을 비교했습니다. 이 수치는 여러 요인이 반영된 결과로, 특정 수정 하나의 효과를 뜻하지는 않습니다.</p></div><Link href="/cases/search-records" className="text-link">작업 내용과 검색 기록 보기 <ArrowRight size={18}/></Link></TabsContent><TabsContent value="content" id="work-panel-content" aria-labelledby="work-tab-content" className="work-panel"><div className="content-scene"><div><p className="kicker">세온비즈 자체 제작</p><h3>써둔 원고로<br/>영상도 만들었습니다.</h3><p>원고에서 꼭 필요한 내용을 골라<br/>약 25초짜리 영상으로 만들었습니다.</p></div><img src="/images/content-poster.png" width="1080" height="1920" loading="lazy" alt="직접 제작한 영상 표지: HTML 변환, 주력 상품부터?"/><img src="/images/content-scene.png" width="1080" height="1920" loading="lazy" alt="영상의 다음 장면: 계속 팔 수 있어야 하니까"/></div><div className="work-caption"><h3>글 한 편을 여러 곳에 활용하는 방법</h3><p>세온비즈가 직접 제작한 영상입니다. 원고를 나누고 장면을 구성한 과정을 소개합니다. 고객의 코칭 성과 자료는 아닙니다.</p></div><Link href="/cases/content-workflow" className="text-link">영상 제작 과정 보기 <ArrowRight size={18}/></Link></TabsContent></div></Tabs></div></section>}
const methodSteps=[
 {label:'상황 듣기',title:'지금 하시는 일을 보여주세요.',body:'운영 중인 사이트나 쓰다 만 글을 같이 봅니다. 광고 결과가 궁금하시면 관리 화면을 열어주세요. 설명을 듣고 어디서부터 살펴볼지 짚어드립니다.',tag:'쓰고 계신 사이트와 자료로'},
 {label:'작업 정하기',title:'이번 시간에 할 일을 정합니다.',body:'상품 설명을 고칠지, 광고 설정을 볼지, 글 한 편을 쓸지 정합니다. 필요한 자료가 준비되어 있는지도 확인하고, 코칭 시간 안에 할 수 있는 만큼 진행합니다.',tag:'이번에 할 일부터 정하고'},
 {label:'직접 해보기',title:'설명을 들으면서 따라 해보세요.',body:'상품 정보와 작업 자료를 AI에 넣고, 나온 답을 고쳐봅니다. 어디를 눌러야 하는지, 어떤 말을 입력해야 하는지 알려드립니다. 대표님 계정으로 작업할 때는 화면을 공유하며 직접 따라 해보세요.',tag:'한 단계씩 직접 해보며'},
 {label:'내용 정리',title:'코칭에서 한 일을 정리해드립니다.',body:'작업한 내용과 코칭이 끝난 뒤 직접 해볼 일을 적어드립니다. 월 코칭에서는 직접 해본 결과를 보고, 잘 안 된 부분을 다시 설명하거나 고칩니다.',tag:'나중에 볼 수 있게 정리합니다'}
];
export function Method(){const [active,setActive]=useState(0);const rows=useRef<(HTMLDivElement|null)[]>([]);useEffect(()=>{const obs=new IntersectionObserver(es=>{const entry=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(entry)setActive(Number((entry.target as HTMLElement).dataset.step))},{rootMargin:'-22% 0px -42% 0px',threshold:[0,.2,.6]});rows.current.forEach(e=>e&&obs.observe(e));return()=>obs.disconnect()},[]);return <section className="method-section container section" id="method"><div className="method-sticky"><p className="eyebrow">일대일 코칭 진행 방식</p><h2>설명을 듣고,<br/>그 자리에서 해보세요.</h2><div className="method-art"><img src="/images/coaching-session.webp" width="1448" height="1086" alt="자료를 함께 살펴보며 작업하는 코칭" loading="lazy" style={{transform:`scale(${1+active*.025}) translateX(${-active*3}px)`}}/><span className="method-art-caption" aria-live="polite">{methodSteps[active].tag}</span></div><p className="muted">Zoom으로 화면을 공유하며 진행합니다.<br/>코칭은 한 번에 2시간입니다.</p></div><div className="method-steps">{methodSteps.map((step,i)=><div key={step.label} ref={el=>{rows.current[i]=el}} data-step={i} className={`method-step ${active===i?'is-active':''}`}><span className="step-index">0{i+1} / {step.label}</span><h3>{step.title}</h3><p>{step.body}</p></div>)}</div></section>}
export function Pricing(){return <section className="pricing section" id="pricing"><div className="container"><div className="section-heading"><p className="eyebrow">코칭 신청 안내</p><h2>코칭 시간과 비용</h2><p>먼저 한 시간 무료로 상담합니다.<br/>어떤 도움이 필요한지 이야기 나눈 뒤 코칭을 선택하시면 됩니다.</p></div><div className="price-table"><article className="price-row"><div><span className="kicker">코칭을 신청하시기 전에</span><h3>첫 무료 상담</h3></div><p>하시려는 일을 듣고 코칭 가능 여부 안내<br/><span className="muted">상담 후 코칭을 받을지 결정하세요. 상세 보고서 작성이나 실제 수정·제작은 유료 코칭에서 진행합니다.</span></p><div className="price-value"><strong>무료</strong><span>1시간</span></div></article><article className="price-row"><div><span className="kicker">보통 주 1회, 한 달 동안</span><h3>월 코칭</h3></div><p>월 4회 × 회당 2시간 · 총 8시간<br/><span className="muted">직접 해본 내용을 다음 코칭에서 점검합니다. 한 달 단위로 신청하며, 연장 여부는 매월 결정합니다.</span></p><div className="price-value"><strong>132<span>만 원</span></strong><span>공급가 120만 원 + 부가세 12만 원</span></div></article><article className="price-row"><div><span className="kicker">필요한 일 한 가지에 집중</span><h3>단독 코칭</h3></div><p>1회 2시간 · 문제 점검과 수정·설정 실습<br/><span className="muted">상품 설명이나 광고 설정 등 필요한 일을 골라 진행합니다. 2시간 안에 할 수 있는 작업을 정하고 시작합니다.</span></p><div className="price-value"><strong>44<span>만 원</span></strong><span>공급가 40만 원 + 부가세 4만 원</span></div></article></div><p className="price-footnote">위 금액은 부가세를 포함한 금액입니다. 5주인 달에도 월 코칭은 4회 진행합니다. 규모가 큰 별도 제작은 작업 내용과 비용을 따로 협의합니다.</p><div className="working-terms"><div><h3>코칭 사이에 생긴 질문은 카카오톡으로</h3><p>질문을 남겨주시면 카카오톡으로 답변드립니다. 메시지로 답하기 어렵거나 추가 작업이 필요한 경우에는 코칭 시간에 설명하고 진행합니다.</p></div><div><h3>AI 구독료와 기타 비용</h3><p>세온비즈 계정으로 작업할 때는 세온비즈가 AI 구독료를 냅니다. 고객 화면과 계정에서 작업할 때는 고객이 구독료를 부담합니다. 광고비, 도메인·호스팅 비용 등은 코칭료에 포함되지 않으며 고객 부담입니다.</p></div></div></div></section>}
const commonFaq=[
 ['AI를 처음 써보는데 괜찮나요?','네. 사용해보신 프로그램이 있는지부터 여쭤보고, 필요한 기능을 하나씩 알려드립니다. 실제 작업을 하면서 배우는 방식이라 코칭 중에는 직접 화면을 조작해보셔야 합니다.'],
 ['무엇부터 해야 할지 모르겠어도 상담할 수 있나요?','네. 현재 하시는 일과 어려운 점을 말씀해주세요. “쇼핑몰을 고치고 싶은데 뭘 고쳐야 할지 모르겠다” 정도로 설명해주셔도 됩니다. 이야기를 듣고 코칭에서 도와드릴 수 있는지 말씀드리겠습니다.'],
 ['무료 상담만 받아도 되나요?','네. 한 시간 상담하신 뒤 코칭을 받을지 결정하시면 됩니다. 상담을 신청했다고 결제되는 일은 없습니다. 실제 수정·제작이나 상세 보고서 작성은 유료 코칭에서 진행합니다.'],
 ['작업을 대신 해주는 건가요?','필요한 초기 작업과 검토는 세온비즈가 도와드리고, 고객도 직접 해보면서 방법을 익힙니다. 전부 맡겨놓고 결과물만 받는 방식은 아닙니다. 규모가 큰 제작을 맡기고 싶으시면 작업 내용과 견적을 별도로 협의합니다.'],
 ['한 달이면 어느 정도 배울 수 있나요?','지금 얼마나 익숙하신지, 어떤 자료가 준비돼 있는지에 따라 다릅니다. 시작할 때 이번 달에 할 일을 정하고 월 4회에 걸쳐 진행합니다. 단독 코칭은 한 가지 작업에 2시간을 쓰는 방식입니다.'],
 ['신청하면 언제 상담하나요?','신청 내용을 읽어본 뒤 휴대전화번호로 카카오톡 연락을 드립니다. 가능한 날짜와 시간을 맞춘 다음 Zoom에서 상담합니다. 카카오톡 연결이 어려우면 문자로 안내드립니다.']
];
export function FAQ(){return <section className="container section faq-section"><h2>자주 묻는 질문</h2><Accordion type="single" collapsible className="faq-list">{commonFaq.map(([q,a],i)=><AccordionItem key={q} value={`faq-${i}`}><AccordionTrigger id={`faq-question-${i}`} aria-controls={`faq-answer-${i}`}>{q}</AccordionTrigger><AccordionContent id={`faq-answer-${i}`} aria-labelledby={`faq-question-${i}`}>{a}</AccordionContent></AccordionItem>)}</Accordion></section>}
export function ConsultCTA(){return <section className="consult-cta"><div className="container"><p className="eyebrow">첫 상담 1시간 무료</p><h2>어떤 일이 필요한지<br/>먼저 들려주세요.</h2><p>사이트 주소와 상담하고 싶은 내용을 남겨주세요.<br/>코칭으로 도와드릴 수 있는지, 어떻게 시작하면 좋을지 말씀드리겠습니다.</p><Link className="button button-coral" href="/apply">1시간 무료 상담 신청 <ArrowUpRight size={20}/></Link></div></section>}
