"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { Menu, ArrowUpRight, ChevronDown, X } from "lucide-react";
import { Sheet, SheetTrigger, SheetContent, SheetTitle, SheetDescription, SheetClose } from "@/components/ui/sheet";
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu";
const links = [["/coaching/shop","쇼핑몰 코칭"],["/coaching/service","서비스업 코칭"],["/process","진행·비용"],["/cases","실제 사례"],["/notes","코칭 노트"],["/about","소개"]];
export function SiteHeader(){
 const [open,setOpen]=useState(false); const path=usePathname();
 return <header className="site-header"><div className="container header-inner"><Link className="wordmark" href="/" aria-label="세온비즈 홈">세온비즈<span>.</span></Link><nav className="desktop-nav" aria-label="주 메뉴"><DropdownMenu><DropdownMenuTrigger id="coaching-menu-trigger" className="nav-trigger">코칭 안내 <ChevronDown size={15}/></DropdownMenuTrigger><DropdownMenuContent align="start" className="nav-popover">{links.slice(0,2).map(([href,label])=><DropdownMenuItem asChild key={href}><Link href={href}>{label}</Link></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>{links.slice(2).map(([href,label])=><Link key={href} href={href} aria-current={path.startsWith(href)?"page":undefined}>{label}</Link>)}<Link href="/apply" className="button button-small button-ink">무료 상담 신청 <ArrowUpRight size={17}/></Link></nav><div className="mobile-nav"><Link className="mobile-consult" href="/apply">무료 상담</Link><Sheet open={open} onOpenChange={setOpen}><SheetTrigger className="icon-button" aria-label="메뉴 열기" aria-controls="mobile-navigation"><Menu/></SheetTrigger><SheetContent id="mobile-navigation" aria-labelledby="mobile-navigation-title" aria-describedby="mobile-navigation-description" className="mobile-sheet" showCloseButton={false}><SheetClose className="icon-button sheet-close" aria-label="메뉴 닫기"><X/></SheetClose><SheetTitle id="mobile-navigation-title" className="wordmark">세온비즈.</SheetTitle><SheetDescription id="mobile-navigation-description" className="sr-only">코칭 안내와 사례, 상담 신청</SheetDescription><nav aria-label="모바일 메뉴">{links.map(([href,label])=><Link key={href} href={href} onClick={()=>setOpen(false)}>{label}<ArrowUpRight size={20}/></Link>)}<Link href="/apply" onClick={()=>setOpen(false)}>1시간 무료 상담<ArrowUpRight size={20}/></Link></nav></SheetContent></Sheet></div></div></header>;
}
export function SiteFooter(){return <footer className="site-footer"><div className="container footer-top"><Link href="/" className="wordmark">세온비즈<span>.</span></Link><p>홈페이지부터 홍보까지,<br/>내 사업에 쓰는 AI 코칭.</p><div><Link href="/coaching/shop">쇼핑몰 코칭</Link><Link href="/coaching/service">서비스업 코칭</Link></div><div><Link href="/cases">실제 사례</Link><Link href="/notes">코칭 노트</Link><Link href="/process">진행·비용</Link><Link href="/about">세온비즈 소개</Link><Link href="/apply">무료 상담 신청</Link></div></div><div className="container footer-company"><span>운영 · 주식회사 티오엠</span><a href="mailto:cobaltblue872@gmail.com">cobaltblue872@gmail.com</a><a href="https://seoncoder.com/" target="_blank" rel="noopener noreferrer">상세페이지 제작 · 세온코더 ↗</a></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} SEONBIZ</span><Link href="/privacy">개인정보처리방침</Link><Link href="/process#changes">변경·취소·환불 안내</Link><span>seonbiz.com</span></div></footer>}
