"use client";
import { useState } from "react";
import { BrandLogo } from "@/components/site/brand-logo";
import { Menu, ArrowUpRight, X } from "lucide-react";
import { Sheet, SheetTrigger, SheetContent, SheetTitle, SheetDescription, SheetClose } from "@/components/ui/sheet";
const links = [["/coaching/website","홈페이지 코칭"],["/process","진행·비용"],["/cases","실제 데이터"],["/notes","코칭 노트"],["/about","소개"]];
export function SiteHeader({pathname}:{pathname:string}){
 const [open,setOpen]=useState(false); const path=pathname;
 return <header className="site-header"><div className="container header-inner"><a className="wordmark" href="/" aria-label="세온비즈 홈"><BrandLogo decorative /></a><nav className="desktop-nav" aria-label="주 메뉴">{links.map(([href,label])=><a key={href} href={href} aria-current={path.startsWith(href)?"page":undefined}>{label}</a>)}<a href="/apply" className="button button-small button-ink">무료 상담 신청 <ArrowUpRight size={17}/></a></nav><div className="mobile-nav"><a className="mobile-consult" href="/apply">무료 상담</a><Sheet open={open} onOpenChange={setOpen}><SheetTrigger className="icon-button" aria-label="메뉴 열기" aria-controls="mobile-navigation"><Menu/></SheetTrigger><SheetContent id="mobile-navigation" aria-labelledby="mobile-navigation-title" aria-describedby="mobile-navigation-description" className="mobile-sheet" showCloseButton={false}><SheetClose className="icon-button sheet-close" aria-label="메뉴 닫기"><X/></SheetClose><SheetTitle id="mobile-navigation-title" className="wordmark"><BrandLogo decorative /><span className="sr-only">세온비즈 메뉴</span></SheetTitle><SheetDescription id="mobile-navigation-description" className="sr-only">코칭 안내와 데이터, 상담 신청</SheetDescription><nav aria-label="모바일 메뉴">{links.map(([href,label])=><a key={href} href={href} onClick={()=>setOpen(false)}>{label}<ArrowUpRight size={20}/></a>)}<a href="/apply" onClick={()=>setOpen(false)}>1시간 무료 상담<ArrowUpRight size={20}/></a></nav></SheetContent></Sheet></div></div></header>;
}
export function SiteFooter(){return <footer className="site-footer"><div className="container footer-top"><a href="/" className="wordmark" aria-label="세온비즈 홈"><BrandLogo decorative /></a><p>제작부터 검색과 운영까지,<br/>내 사업에 쓰는 홈페이지 AI 코칭.</p><div><a href="/coaching/website">홈페이지 코칭</a><a href="/cases">실제 데이터</a></div><div><a href="/notes">코칭 노트</a><a href="/process">진행·비용</a><a href="/about">세온비즈 소개</a><a href="/apply">무료 상담 신청</a></div></div><div className="container footer-company"><span>운영 · 주식회사 티오엠</span><a href="mailto:cobaltblue872@gmail.com">cobaltblue872@gmail.com</a></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} SEONBIZ</span><a href="/privacy">개인정보처리방침</a><a href="/process#changes">변경·취소·환불 안내</a><span>seonbiz.com</span></div></footer>}
